//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.5.96
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "a4bce39368456b87")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>BaseCore</summary>
	[PublishedContentModel("baseCore")]
	public partial class BaseCore : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "baseCore";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BaseCore(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BaseCore, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>BasePage</summary>
	[PublishedContentModel("basePage")]
	public partial class BasePage : BaseCore
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "basePage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BasePage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BasePage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HideFromMenu
		///</summary>
		[ImplementPropertyType("hideFromMenu")]
		public bool HideFromMenu
		{
			get { return this.GetPropertyValue<bool>("hideFromMenu"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public Umbraco.Web.Models.ImageCropDataSet Image
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("image"); }
		}

		///<summary>
		/// ImageName
		///</summary>
		[ImplementPropertyType("imageName_bg")]
		public string ImageName_bg
		{
			get { return this.GetPropertyValue<string>("imageName_bg"); }
		}

		///<summary>
		/// ImageName
		///</summary>
		[ImplementPropertyType("imageName_en")]
		public string ImageName_en
		{
			get { return this.GetPropertyValue<string>("imageName_en"); }
		}

		///<summary>
		/// ImageName
		///</summary>
		[ImplementPropertyType("imageName_mk")]
		public string ImageName_mk
		{
			get { return this.GetPropertyValue<string>("imageName_mk"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_bg")]
		public IHtmlString RichTextEditor_bg
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_bg"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_en")]
		public IHtmlString RichTextEditor_en
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_en"); }
		}

		///<summary>
		/// RichTextEditor
		///</summary>
		[ImplementPropertyType("richTextEditor_mk")]
		public IHtmlString RichTextEditor_mk
		{
			get { return this.GetPropertyValue<IHtmlString>("richTextEditor_mk"); }
		}

		///<summary>
		/// ShortDescription
		///</summary>
		[ImplementPropertyType("shortDescription_bg")]
		public string ShortDescription_bg
		{
			get { return this.GetPropertyValue<string>("shortDescription_bg"); }
		}

		///<summary>
		/// ShortDescription
		///</summary>
		[ImplementPropertyType("shortDescription_en")]
		public string ShortDescription_en
		{
			get { return this.GetPropertyValue<string>("shortDescription_en"); }
		}

		///<summary>
		/// ShortDescription
		///</summary>
		[ImplementPropertyType("shortDescription_mk")]
		public string ShortDescription_mk
		{
			get { return this.GetPropertyValue<string>("shortDescription_mk"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_bg")]
		public string Title_bg
		{
			get { return this.GetPropertyValue<string>("title_bg"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_en")]
		public string Title_en
		{
			get { return this.GetPropertyValue<string>("title_en"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_mk")]
		public string Title_mk
		{
			get { return this.GetPropertyValue<string>("title_mk"); }
		}
	}

	/// <summary>Articles</summary>
	[PublishedContentModel("articles")]
	public partial class Articles : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "articles";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Articles(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Articles, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Gallery
		///</summary>
		[ImplementPropertyType("mediaPicker")]
		public string MediaPicker
		{
			get { return this.GetPropertyValue<string>("mediaPicker"); }
		}
	}

	/// <summary>Accomodation</summary>
	[PublishedContentModel("accomodation")]
	public partial class Accomodation : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "accomodation";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Accomodation(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Accomodation, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Capacity
		///</summary>
		[ImplementPropertyType("capacity_bg")]
		public string Capacity_bg
		{
			get { return this.GetPropertyValue<string>("capacity_bg"); }
		}

		///<summary>
		/// Capacity
		///</summary>
		[ImplementPropertyType("capacity_en")]
		public string Capacity_en
		{
			get { return this.GetPropertyValue<string>("capacity_en"); }
		}

		///<summary>
		/// Capacity
		///</summary>
		[ImplementPropertyType("capacity_mk")]
		public string Capacity_mk
		{
			get { return this.GetPropertyValue<string>("capacity_mk"); }
		}

		///<summary>
		/// Category
		///</summary>
		[ImplementPropertyType("category")]
		public object Category
		{
			get { return this.GetPropertyValue("category"); }
		}

		///<summary>
		/// Contact
		///</summary>
		[ImplementPropertyType("contact_bg")]
		public string Contact_bg
		{
			get { return this.GetPropertyValue<string>("contact_bg"); }
		}

		///<summary>
		/// Contact
		///</summary>
		[ImplementPropertyType("contact_en")]
		public string Contact_en
		{
			get { return this.GetPropertyValue<string>("contact_en"); }
		}

		///<summary>
		/// Contact
		///</summary>
		[ImplementPropertyType("contact_mk")]
		public string Contact_mk
		{
			get { return this.GetPropertyValue<string>("contact_mk"); }
		}

		///<summary>
		/// Gallery
		///</summary>
		[ImplementPropertyType("gallery_bg")]
		public string Gallery_bg
		{
			get { return this.GetPropertyValue<string>("gallery_bg"); }
		}

		///<summary>
		/// Gallery
		///</summary>
		[ImplementPropertyType("gallery_en")]
		public string Gallery_en
		{
			get { return this.GetPropertyValue<string>("gallery_en"); }
		}

		///<summary>
		/// Gallery
		///</summary>
		[ImplementPropertyType("gallery_mk")]
		public object Gallery_mk
		{
			get { return this.GetPropertyValue("gallery_mk"); }
		}
	}

	/// <summary>News</summary>
	[PublishedContentModel("news")]
	public partial class News : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "news";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public News(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<News, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// DateTime
		///</summary>
		[ImplementPropertyType("dateTime")]
		public DateTime DateTime
		{
			get { return this.GetPropertyValue<DateTime>("dateTime"); }
		}

		///<summary>
		/// Gallery
		///</summary>
		[ImplementPropertyType("gallery")]
		public string Gallery
		{
			get { return this.GetPropertyValue<string>("gallery"); }
		}
	}

	/// <summary>Gallery</summary>
	[PublishedContentModel("gallery")]
	public partial class Gallery : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "gallery";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Gallery(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Gallery, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FileUpload
		///</summary>
		[ImplementPropertyType("fileUpload")]
		public object FileUpload
		{
			get { return this.GetPropertyValue("fileUpload"); }
		}

		///<summary>
		/// MediaPicker
		///</summary>
		[ImplementPropertyType("mediaPicker")]
		public string MediaPicker
		{
			get { return this.GetPropertyValue<string>("mediaPicker"); }
		}

		///<summary>
		/// RelatedLinks
		///</summary>
		[ImplementPropertyType("relatedLinks")]
		public Newtonsoft.Json.Linq.JArray RelatedLinks
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JArray>("relatedLinks"); }
		}
	}

	/// <summary>Contact Us</summary>
	[PublishedContentModel("contactUs")]
	public partial class ContactUs : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "contactUs";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContactUs(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContactUs, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address_bg")]
		public string Address_bg
		{
			get { return this.GetPropertyValue<string>("address_bg"); }
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address_en")]
		public string Address_en
		{
			get { return this.GetPropertyValue<string>("address_en"); }
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address_mk")]
		public string Address_mk
		{
			get { return this.GetPropertyValue<string>("address_mk"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email_bg")]
		public string Email_bg
		{
			get { return this.GetPropertyValue<string>("email_bg"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email_en")]
		public string Email_en
		{
			get { return this.GetPropertyValue<string>("email_en"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email_mk")]
		public string Email_mk
		{
			get { return this.GetPropertyValue<string>("email_mk"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone_bg")]
		public string Phone_bg
		{
			get { return this.GetPropertyValue<string>("phone_bg"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone_en")]
		public string Phone_en
		{
			get { return this.GetPropertyValue<string>("phone_en"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone_mk")]
		public string Phone_mk
		{
			get { return this.GetPropertyValue<string>("phone_mk"); }
		}
	}

	/// <summary>GenericPage</summary>
	[PublishedContentModel("genericPage")]
	public partial class GenericPage : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "genericPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GenericPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GenericPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Home</summary>
	[PublishedContentModel("home")]
	public partial class Home : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "home";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Home(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Home, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Event</summary>
	[PublishedContentModel("event")]
	public partial class Event : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "event";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Event(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Event, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Ascend
		///</summary>
		[ImplementPropertyType("ascend_bg")]
		public string Ascend_bg
		{
			get { return this.GetPropertyValue<string>("ascend_bg"); }
		}

		///<summary>
		/// Ascend
		///</summary>
		[ImplementPropertyType("ascend_en")]
		public string Ascend_en
		{
			get { return this.GetPropertyValue<string>("ascend_en"); }
		}

		///<summary>
		/// Ascend
		///</summary>
		[ImplementPropertyType("ascend_mk")]
		public string Ascend_mk
		{
			get { return this.GetPropertyValue<string>("ascend_mk"); }
		}

		///<summary>
		/// DateOfEvent
		///</summary>
		[ImplementPropertyType("dateOfEvent")]
		public DateTime DateOfEvent
		{
			get { return this.GetPropertyValue<DateTime>("dateOfEvent"); }
		}

		///<summary>
		/// Descend
		///</summary>
		[ImplementPropertyType("descend_bg")]
		public string Descend_bg
		{
			get { return this.GetPropertyValue<string>("descend_bg"); }
		}

		///<summary>
		/// Descend
		///</summary>
		[ImplementPropertyType("descend_en")]
		public string Descend_en
		{
			get { return this.GetPropertyValue<string>("descend_en"); }
		}

		///<summary>
		/// Descend
		///</summary>
		[ImplementPropertyType("descend_mk")]
		public string Descend_mk
		{
			get { return this.GetPropertyValue<string>("descend_mk"); }
		}

		///<summary>
		/// Distans
		///</summary>
		[ImplementPropertyType("distans_bg")]
		public string Distans_bg
		{
			get { return this.GetPropertyValue<string>("distans_bg"); }
		}

		///<summary>
		/// Distans
		///</summary>
		[ImplementPropertyType("distans_en")]
		public string Distans_en
		{
			get { return this.GetPropertyValue<string>("distans_en"); }
		}

		///<summary>
		/// Distans
		///</summary>
		[ImplementPropertyType("distans_mk")]
		public string Distans_mk
		{
			get { return this.GetPropertyValue<string>("distans_mk"); }
		}

		///<summary>
		/// EndPoint
		///</summary>
		[ImplementPropertyType("endPoint_bg")]
		public string EndPoint_bg
		{
			get { return this.GetPropertyValue<string>("endPoint_bg"); }
		}

		///<summary>
		/// EndPoint
		///</summary>
		[ImplementPropertyType("endPoint_en")]
		public string EndPoint_en
		{
			get { return this.GetPropertyValue<string>("endPoint_en"); }
		}

		///<summary>
		/// EndPoint
		///</summary>
		[ImplementPropertyType("endPoint_mk")]
		public string EndPoint_mk
		{
			get { return this.GetPropertyValue<string>("endPoint_mk"); }
		}

		///<summary>
		/// HideFromMenuStatistic
		///</summary>
		[ImplementPropertyType("hideFromMenuStatistic")]
		public bool HideFromMenuStatistic
		{
			get { return this.GetPropertyValue<bool>("hideFromMenuStatistic"); }
		}

		///<summary>
		/// HighestPoint
		///</summary>
		[ImplementPropertyType("highestPoint_bg")]
		public string HighestPoint_bg
		{
			get { return this.GetPropertyValue<string>("highestPoint_bg"); }
		}

		///<summary>
		/// HighestPoint
		///</summary>
		[ImplementPropertyType("highestPoint_en")]
		public string HighestPoint_en
		{
			get { return this.GetPropertyValue<string>("highestPoint_en"); }
		}

		///<summary>
		/// HighestPoint
		///</summary>
		[ImplementPropertyType("highestPoint_mk")]
		public string HighestPoint_mk
		{
			get { return this.GetPropertyValue<string>("highestPoint_mk"); }
		}

		///<summary>
		/// Is Payment
		///</summary>
		[ImplementPropertyType("isPayment")]
		public bool IsPayment
		{
			get { return this.GetPropertyValue<bool>("isPayment"); }
		}

		///<summary>
		/// LocationCoordinates LAT
		///</summary>
		[ImplementPropertyType("locationCoordinatesLAT")]
		public string LocationCoordinatesLat
		{
			get { return this.GetPropertyValue<string>("locationCoordinatesLAT"); }
		}

		///<summary>
		/// LocationCoordinatesLON
		///</summary>
		[ImplementPropertyType("locationCoordinatesLON")]
		public string LocationCoordinatesLon
		{
			get { return this.GetPropertyValue<string>("locationCoordinatesLON"); }
		}

		///<summary>
		/// LowestPoint
		///</summary>
		[ImplementPropertyType("lowestPoint_bg")]
		public string LowestPoint_bg
		{
			get { return this.GetPropertyValue<string>("lowestPoint_bg"); }
		}

		///<summary>
		/// LowestPoint
		///</summary>
		[ImplementPropertyType("lowestPoint_en")]
		public string LowestPoint_en
		{
			get { return this.GetPropertyValue<string>("lowestPoint_en"); }
		}

		///<summary>
		/// LowestPoint
		///</summary>
		[ImplementPropertyType("lowestPoint_mk")]
		public string LowestPoint_mk
		{
			get { return this.GetPropertyValue<string>("lowestPoint_mk"); }
		}

		///<summary>
		/// Show Participants
		///</summary>
		[ImplementPropertyType("showParticipants")]
		public bool ShowParticipants
		{
			get { return this.GetPropertyValue<bool>("showParticipants"); }
		}

		///<summary>
		/// StartingPoint
		///</summary>
		[ImplementPropertyType("startingPoint_bg")]
		public string StartingPoint_bg
		{
			get { return this.GetPropertyValue<string>("startingPoint_bg"); }
		}

		///<summary>
		/// StartingPoint
		///</summary>
		[ImplementPropertyType("startingPoint_en")]
		public string StartingPoint_en
		{
			get { return this.GetPropertyValue<string>("startingPoint_en"); }
		}

		///<summary>
		/// StartingPoint
		///</summary>
		[ImplementPropertyType("startingPoint_mk")]
		public string StartingPoint_mk
		{
			get { return this.GetPropertyValue<string>("startingPoint_mk"); }
		}

		///<summary>
		/// TimeLimit
		///</summary>
		[ImplementPropertyType("timeLimit_bg")]
		public string TimeLimit_bg
		{
			get { return this.GetPropertyValue<string>("timeLimit_bg"); }
		}

		///<summary>
		/// TimeLimit
		///</summary>
		[ImplementPropertyType("timeLimit_en")]
		public string TimeLimit_en
		{
			get { return this.GetPropertyValue<string>("timeLimit_en"); }
		}

		///<summary>
		/// TimeLimit
		///</summary>
		[ImplementPropertyType("timeLimit_mk")]
		public string TimeLimit_mk
		{
			get { return this.GetPropertyValue<string>("timeLimit_mk"); }
		}
	}

	/// <summary>ContainerGeneral</summary>
	[PublishedContentModel("containerGeneral")]
	public partial class ContainerGeneral : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerGeneral";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerGeneral(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerGeneral, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerNews</summary>
	[PublishedContentModel("containerNews")]
	public partial class ContainerNews : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerNews";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerNews(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerNews, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerArticles</summary>
	[PublishedContentModel("containerArticles")]
	public partial class ContainerArticles : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerArticles";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerArticles(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerArticles, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerGalleries</summary>
	[PublishedContentModel("containerGalleries")]
	public partial class ContainerGalleries : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerGalleries";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerGalleries(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerGalleries, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerAccommodations</summary>
	[PublishedContentModel("containerAccommodations")]
	public partial class ContainerAccommodations : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerAccommodations";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerAccommodations(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerAccommodations, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerArchivedEvents</summary>
	[PublishedContentModel("containerArchivedEvents")]
	public partial class ContainerArchivedEvents : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerArchivedEvents";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerArchivedEvents(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerArchivedEvents, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerEvents</summary>
	[PublishedContentModel("containerEvents")]
	public partial class ContainerEvents : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerEvents";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerEvents(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerEvents, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// DateOfEvent
		///</summary>
		[ImplementPropertyType("dateOfEvent")]
		public DateTime DateOfEvent
		{
			get { return this.GetPropertyValue<DateTime>("dateOfEvent"); }
		}

		///<summary>
		/// T-shirts Limit Count
		///</summary>
		[ImplementPropertyType("tshirtsLimitCount")]
		public int TshirtsLimitCount
		{
			get { return this.GetPropertyValue<int>("tshirtsLimitCount"); }
		}
	}

	/// <summary>ContainerNatures</summary>
	[PublishedContentModel("containerNatures")]
	public partial class ContainerNatures : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerNatures";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerNatures(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerNatures, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerSettlements</summary>
	[PublishedContentModel("containerSettlements")]
	public partial class ContainerSettlements : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerSettlements";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerSettlements(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerSettlements, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerTourists</summary>
	[PublishedContentModel("containerTourists")]
	public partial class ContainerTourists : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerTourists";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerTourists(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerTourists, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ContainerCultures</summary>
	[PublishedContentModel("containerCultures")]
	public partial class ContainerCultures : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerCultures";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerCultures(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerCultures, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>ImageBaner</summary>
	[PublishedContentModel("imageBaner")]
	public partial class ImageBaner : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "imageBaner";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ImageBaner(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ImageBaner, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description_bg")]
		public string Description_bg
		{
			get { return this.GetPropertyValue<string>("description_bg"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description_en")]
		public string Description_en
		{
			get { return this.GetPropertyValue<string>("description_en"); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("description_mk")]
		public string Description_mk
		{
			get { return this.GetPropertyValue<string>("description_mk"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public Umbraco.Web.Models.ImageCropDataSet Image
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("image"); }
		}

		///<summary>
		/// ShortInfo
		///</summary>
		[ImplementPropertyType("shortInfo_bg")]
		public string ShortInfo_bg
		{
			get { return this.GetPropertyValue<string>("shortInfo_bg"); }
		}

		///<summary>
		/// ShortInfo
		///</summary>
		[ImplementPropertyType("shortInfo_en")]
		public string ShortInfo_en
		{
			get { return this.GetPropertyValue<string>("shortInfo_en"); }
		}

		///<summary>
		/// ShortInfo
		///</summary>
		[ImplementPropertyType("shortInfo_mk")]
		public string ShortInfo_mk
		{
			get { return this.GetPropertyValue<string>("shortInfo_mk"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_bg")]
		public string Title_bg
		{
			get { return this.GetPropertyValue<string>("title_bg"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_en")]
		public string Title_en
		{
			get { return this.GetPropertyValue<string>("title_en"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_mk")]
		public string Title_mk
		{
			get { return this.GetPropertyValue<string>("title_mk"); }
		}
	}

	/// <summary>FileUpload</summary>
	[PublishedContentModel("fileUpload")]
	public partial class FileUpload : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "fileUpload";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FileUpload(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FileUpload, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// FilesUpload
		///</summary>
		[ImplementPropertyType("filesUpload")]
		public object FilesUpload
		{
			get { return this.GetPropertyValue("filesUpload"); }
		}

		///<summary>
		/// ShortInfo
		///</summary>
		[ImplementPropertyType("shortInfo_bg")]
		public string ShortInfo_bg
		{
			get { return this.GetPropertyValue<string>("shortInfo_bg"); }
		}

		///<summary>
		/// ShortInfo
		///</summary>
		[ImplementPropertyType("shortInfo_en")]
		public string ShortInfo_en
		{
			get { return this.GetPropertyValue<string>("shortInfo_en"); }
		}

		///<summary>
		/// ShortInfo
		///</summary>
		[ImplementPropertyType("shortInfo_mk")]
		public string ShortInfo_mk
		{
			get { return this.GetPropertyValue<string>("shortInfo_mk"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_bg")]
		public string Title_bg
		{
			get { return this.GetPropertyValue<string>("title_bg"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_en")]
		public string Title_en
		{
			get { return this.GetPropertyValue<string>("title_en"); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title_mk")]
		public string Title_mk
		{
			get { return this.GetPropertyValue<string>("title_mk"); }
		}
	}

	/// <summary>ContainerEventWrap</summary>
	[PublishedContentModel("containerEventWrap")]
	public partial class ContainerEventWrap : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "containerEventWrap";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ContainerEventWrap(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ContainerEventWrap, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Route KML</summary>
	[PublishedContentModel("umbRouteKMLDocType")]
	public partial class UmbRouteKmldocType : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbRouteKMLDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbRouteKmldocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbRouteKmldocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// KML File Upload: Allowed extensions KML
		///</summary>
		[ImplementPropertyType("kmlRouteFileUpload")]
		public object KmlRouteFileUpload
		{
			get { return this.GetPropertyValue("kmlRouteFileUpload"); }
		}
	}

	/// <summary>Members List Per Route</summary>
	[PublishedContentModel("umbMembersListDocType")]
	public partial class UmbMembersListDocType : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbMembersListDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbMembersListDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbMembersListDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Login</summary>
	[PublishedContentModel("login")]
	public partial class Login : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "login";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Login(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Login, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// HideFromLoginAge
		///</summary>
		[ImplementPropertyType("hideFromLoginAge")]
		public bool HideFromLoginAge
		{
			get { return this.GetPropertyValue<bool>("hideFromLoginAge"); }
		}

		///<summary>
		/// HideFromLoginBirthDay
		///</summary>
		[ImplementPropertyType("hideFromLoginBirthDay")]
		public bool HideFromLoginBirthDay
		{
			get { return this.GetPropertyValue<bool>("hideFromLoginBirthDay"); }
		}

		///<summary>
		/// HideFromLoginCity
		///</summary>
		[ImplementPropertyType("hideFromLoginCity")]
		public bool HideFromLoginCity
		{
			get { return this.GetPropertyValue<bool>("hideFromLoginCity"); }
		}

		///<summary>
		/// HideFromLoginClub
		///</summary>
		[ImplementPropertyType("hideFromLoginClub")]
		public bool HideFromLoginClub
		{
			get { return this.GetPropertyValue<bool>("hideFromLoginClub"); }
		}

		///<summary>
		/// HideFromLoginPassportID
		///</summary>
		[ImplementPropertyType("hideFromLoginPassportID")]
		public bool HideFromLoginPassportID
		{
			get { return this.GetPropertyValue<bool>("hideFromLoginPassportID"); }
		}
	}

	/// <summary>MembersListAdminSection</summary>
	[PublishedContentModel("umbMembersListAdminSectionDocType")]
	public partial class UmbMembersListAdminSectionDocType : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbMembersListAdminSectionDocType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbMembersListAdminSectionDocType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbMembersListAdminSectionDocType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>RealTimeTracking</summary>
	[PublishedContentModel("umbDocTypeRealTimeTracking")]
	public partial class UmbDocTypeRealTimeTracking : BasePage
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbDocTypeRealTimeTracking";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbDocTypeRealTimeTracking(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbDocTypeRealTimeTracking, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// RouteFolder: Long/Short/...
		///</summary>
		[ImplementPropertyType("routeFolderTxt")]
		public string RouteFolderTxt
		{
			get { return this.GetPropertyValue<string>("routeFolderTxt"); }
		}
	}

	/// <summary>ContainerRealTimeTrackings</summary>
	[PublishedContentModel("umbDocTypeContainerRealTimeTrackings")]
	public partial class UmbDocTypeContainerRealTimeTrackings : ContainerGeneral
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "umbDocTypeContainerRealTimeTrackings";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public UmbDocTypeContainerRealTimeTrackings(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<UmbDocTypeContainerRealTimeTrackings, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public object UmbracoFile
		{
			get { return this.GetPropertyValue("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Age
		///</summary>
		[ImplementPropertyType("age")]
		public int Age
		{
			get { return this.GetPropertyValue<int>("age"); }
		}

		///<summary>
		/// BirthDay
		///</summary>
		[ImplementPropertyType("birthDay")]
		public DateTime BirthDay
		{
			get { return this.GetPropertyValue<DateTime>("birthDay"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Club
		///</summary>
		[ImplementPropertyType("club")]
		public string Club
		{
			get { return this.GetPropertyValue<string>("club"); }
		}

		///<summary>
		/// DateTime
		///</summary>
		[ImplementPropertyType("dateTime")]
		public DateTime DateTime
		{
			get { return this.GetPropertyValue<DateTime>("dateTime"); }
		}

		///<summary>
		/// Declaration
		///</summary>
		[ImplementPropertyType("declaration")]
		public bool Declaration
		{
			get { return this.GetPropertyValue<bool>("declaration"); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return this.GetPropertyValue<string>("email"); }
		}

		///<summary>
		/// EventID
		///</summary>
		[ImplementPropertyType("eventID")]
		public object EventID
		{
			get { return this.GetPropertyValue("eventID"); }
		}

		///<summary>
		/// FirstName
		///</summary>
		[ImplementPropertyType("firstName")]
		public string FirstName
		{
			get { return this.GetPropertyValue<string>("firstName"); }
		}

		///<summary>
		/// MaleGender
		///</summary>
		[ImplementPropertyType("gender")]
		public bool Gender
		{
			get { return this.GetPropertyValue<bool>("gender"); }
		}

		///<summary>
		/// isPaid
		///</summary>
		[ImplementPropertyType("isPaid")]
		public bool IsPaid
		{
			get { return this.GetPropertyValue<bool>("isPaid"); }
		}

		///<summary>
		/// LastName
		///</summary>
		[ImplementPropertyType("lastName")]
		public string LastName
		{
			get { return this.GetPropertyValue<string>("lastName"); }
		}

		///<summary>
		/// Nationality
		///</summary>
		[ImplementPropertyType("nationality")]
		public string Nationality
		{
			get { return this.GetPropertyValue<string>("nationality"); }
		}

		///<summary>
		/// PassportIDCardNumber
		///</summary>
		[ImplementPropertyType("passportIDCardNumber")]
		public string PassportIdcardNumber
		{
			get { return this.GetPropertyValue<string>("passportIDCardNumber"); }
		}

		///<summary>
		/// Registration Number
		///</summary>
		[ImplementPropertyType("registartionNumber")]
		public string RegistartionNumber
		{
			get { return this.GetPropertyValue<string>("registartionNumber"); }
		}

		///<summary>
		/// Route
		///</summary>
		[ImplementPropertyType("route")]
		public string Route
		{
			get { return this.GetPropertyValue<string>("route"); }
		}

		///<summary>
		/// TShirtSize
		///</summary>
		[ImplementPropertyType("tShirtSize")]
		public string TShirtSize
		{
			get { return this.GetPropertyValue<string>("tShirtSize"); }
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}
